### ISSUE TITLE
Unable to run on macOS Sonoma

### ISSUE THREAD

**Issue by snorrehu** [kstyrc/embedded-redis#135]
This worked before I upgraded to macOS Sonoma. Now I get this error message:

```
java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log: 

	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
```

**Comment by PengLean** [comment]
have the same problem

**Comment by PengLean** [comment]
> have the same problem

https://github.com/kstyrc/embedded-redis/issues/127#issuecomment-1049823658
I follow the comment to set up local redisExecProvider when create redis server, then solve the problem.

**Comment by EGjaedong** [comment]
same problem with you

**Comment by frankfiorante** [comment]
having the same problem

**Comment by vjsantojaca** [comment]
I have the same problem. I have modified the code in this repository https://github.com/vjsantojaca/embedded-redis and now the tests pass without error (I have not upload it to a maven repository)

_I am trying to update the redis version to a new one._

Anyway, I think that the correct way would be change the dependencies that we have with this library in our repository and use testcontainers.

```
    redis = new GenericContainer(DockerImageName.parse("redis:7.0.0").toString()).withExposedPorts(6379);
    redis.start();

    String host =  redis.getContainerIpAddress();
    Integer port = redis.getMappedPort(6379);

    System.out.println("Redis -> " + host + ":" + port);
```

**Comment by tpanagos** [comment]
@CodeMonstur's build with maven repo worked to fix for me.

https://mvnrepository.com/artifact/com.github.codemonstur/embedded-redis/1.0.0

**Comment by kiesslingh** [comment]
@tpanagos You mean that @codemonstur's build works with macOS Sonoma for you? It doesn't for me, and no wonder: It's of March 17, 2023.

**Comment by fernando-garcia-diaz** [comment]
> @codemonstur's build with maven repo worked to fix for me.
> 
> https://mvnrepository.com/artifact/com.github.codemonstur/embedded-redis/1.0.0

Unfortunately this works in Intel macs but not on M1 macs

**Comment by jevanlingen** [comment]
> Unfortunately this works in Intel macs but not on M1 Macs

Yeah, that's kinda sad. Luckily the customised Redis version by @vjsantojaca does work on my m2 Mac 💪🏻!

**Comment by mamachanko** [comment]
Most likely security policies forbid the Redis binary from starting. The security policies seems to have been tightened in Sonoma. You can confirm that yourself with the _Console_ app. Learn a bit more about it [over here](https://eclecticlight.co/2023/10/07/sonomas-log-gets-briefer-and-more-secretive/). In a nutshell, you start recording messages, filter for `redis` and run whatever code uses `embedded-redis`. Eventually you might see something like this:

```
ASP: Security policy would not allow process <pid>
```

One way to get past this policy is to grant permission to certain programs in the _Developer Tools_ settings. We've been successful in granting `java` permissions. 

![yes-java](https://github.com/kstyrc/embedded-redis/assets/1182927/ce04c371-7fc0-479a-bfd8-7ebff360491c)

You will have to point at your java binary. Depending on how you install it, it will be in different places. `which java` can help. SDKman and brew put binaries in special locations.

Once you grant java with permissions, run your things again but make sure that there are new PIDs. For example, when you use gradle, say `--no-daemon` to not reuse an existing daemon which might not have elevated permissions yet.

❗ Disclaimer: this is potentially unsafe. zero warranty. you have been warned. yak yak.

**Comment by wuyongdec** [comment]
finally it works for me @mamachanko appreciate for your help

**Comment by michaelcowan** [comment]
Another option is to move to a maintained fork that has addressed this issue:
https://github.com/codemonstur/embedded-redis

This worked for me MacOS Sonoma 14.1.1 (23B81) M1.

**Comment by PovilasKM** [comment]
> Another option is to move to a maintained fork that has addressed this issue: https://github.com/codemonstur/embedded-redis
> 
> This worked for me MacOS Sonoma 14.1.1 (23B81) M1.

Thanks, that repo worked for me with 14.1.1 (23B81), 2019 mac.
The only difference between these repos was that RedisServer.builder() had to be replaced with RedisServer.newRedisServer()

**Comment by SanthoshVasabhaktula** [comment]
> Another option is to move to a maintained fork that has addressed this issue: https://github.com/codemonstur/embedded-redis
> 
> This worked for me MacOS Sonoma 14.1.1 (23B81) M1.

Thanks, the same has worked for me with 14.1.1 (23B81) M2 as well

**Comment by Hejow** [comment]
> @codemonstur's build with maven repo worked to fix for me.
> 
> https://mvnrepository.com/artifact/com.github.codemonstur/embedded-redis/1.0.0

Thanks! This works on me (mac M2 pro 14.2.1)

**Comment by deva820** [comment]
I am on Mac M2 Pro Sonoma. But unfortunately it does not work for me. I get the following error while running the builds. I am using latest version 1.4.1. I have also tried 1.0.0 as well.

Caused by: java.io.IOException: Ready pattern not found in log. Startup log: 
        at redis.embedded.RedisInstance.awaitServerReady(RedisInstance.java:59)
        at redis.embedded.RedisInstance.start(RedisInstance.java:45)
        ... 92 more

`  @Bean("EmbeddedRedisConfig")
  public EmbeddedRedisConfig embeddedRedisConfig() throws IOException {
    int redisPort = 6381;
    redisServer = RedisServer.newRedisServer().port(redisPort).build();
    redisServer.start();
    log.info("Started redis server on port {}", redisPort);
    return new EmbeddedRedisConfig(redisServer, redisPort);
  }
`

**Comment by michellemillerh** [comment]
@mamachanko's option worked for me on M1 Airbook, 14.3.1. I had to enable this for both Java and IntelliJ also -- the screenshot hints at IntelliJ but has it turned off. Also, `which java` misled me, it did not show brew's installation path, but `echo $JAVA_HOME` and then /bin/java did.

I wasn't able to use the codemunster fork because it broke in our Jenkins pipeline running on Linux with `java.io.IOException: Ready pattern not found in log. Startup log`.

**Comment by phanker** [comment]
> @mamachanko's option worked for me on M1 Airbook, 14.3.1. I had to enable this for both Java and IntelliJ also -- the screenshot hints at IntelliJ but has it turned off. Also, `which java` misled me, it did not show brew's installation path, but `echo $JAVA_HOME` and then /bin/java did.
> 
> I wasn't able to use the codemunster fork because it broke in our Jenkins pipeline running on Linux with `java.io.IOException: Ready pattern not found in log. Startup log`.

it works for me.

**Comment by codemonstur** [comment]
@michellemillerh 
> I wasn't able to use the codemunster fork because it broke in our Jenkins pipeline running on Linux with `java.io.IOException: Ready pattern not found in log. Startup log`.

This is the error that you get when the Redis binary doesn't start up at all. Theoretically it could be anything but lots of people appear to have trouble because they run the binary on a host that doesn't have libssl.so installed. If you run the latest version of the library it should give you a more detailed error message that says as much. Installing libssl on the host is the solution most people go for.

**Comment by benshenlan** [comment]
> Most likely security policies forbid the Redis binary from starting. The security policies seems to have been tightened in Sonoma. You can confirm that yourself with the _Console_ app. Learn a bit more about it [over here](https://eclecticlight.co/2023/10/07/sonomas-log-gets-briefer-and-more-secretive/). In a nutshell, you start recording messages, filter for `redis` and run whatever code uses `embedded-redis`. Eventually you might see something like this:
> 
> ```
> ASP: Security policy would not allow process <pid>
> ```
> 
> One way to get past this policy is to grant permission to certain programs in the _Developer Tools_ settings. We've been successful in granting `java` permissions.
> 
> ![yes-java](https://private-user-images.githubusercontent.com/1182927/282847075-ce04c371-7fc0-479a-bfd8-7ebff360491c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NzYzMzYsIm5iZiI6MTcyNjk3NjAzNiwicGF0aCI6Ii8xMTgyOTI3LzI4Mjg0NzA3NS1jZTA0YzM3MS03ZmMwLTQ3OWEtYmZkOC03ZWJmZjM2MDQ5MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMDMzMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBkNDkxODViNjU3OGFmODMzMmM4NjdhMjVmN2ExYzAzYTNmOGRhYTg4MDMwNGRmMmU5ODVlN2JmYjBiMmE3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yiV9Lp8Yba4UtzdEWcg-D-7UK_YLmYPaMMLAUj_JuMk)
> 
> You will have to point at your java binary. Depending on how you install it, it will be in different places. `which java` can help. SDKman and brew put binaries in special locations.
> 
> Once you grant java with permissions, run your things again but make sure that there are new PIDs. For example, when you use gradle, say `--no-daemon` to not reuse an existing daemon which might not have elevated permissions yet.
> 
> ❗ Disclaimer: this is potentially unsafe. zero warranty. you have been warned. yak yak.

Thanks a lot !  
I grant java and IDEA permission  and it works !
