### ISSUE TITLE
Running on Windows Server 2008

### ISSUE THREAD

**Issue by dalilagauge** [kstyrc/embedded-redis#70]
I have Jenkins installed on Windows Server 2008.
When I run my unit tests on local machine, I have success. But, when I run on Jenkins I have this error:

java.lang.RuntimeException: Can't start redis server. Check logs for details.
        at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:61)
        at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39)
        at redis.embedded.RedisServer.start(RedisServer.java:9)
        at teste.Main.main(Main.java:13)

The settings of RedisServer are the same.
What is wrong?
I try to show a complete log error, but I dont get.

**Comment by casidiablo** [comment]
Make sure there's no redis process running, bound to the same port. Also, make sure to kill the redis processes once you are done with them.

See https://github.com/kstyrc/embedded-redis/issues/51

**Comment by dalilagauge** [comment]
After a long time of tests.....I have success!
I read #51 and see the problem with maxheap.
I set the value of maxheap and the problem is solved.
The command is:

RedisServer server = new RedisServerBuilder().setting("maxheap 512Mb").port(6370).build();

Thanks for your help!
I hope help other people.

**Comment by jaceko** [comment]
Thanks @dalilagauge for posting this.
It helped me as well.
