### ISSUE TITLE
Cannot start Redis server on AIX/Windows

### ISSUE THREAD

**Issue by tdiesler** [kstyrc/embedded-redis#80]
```
2017-03-17 19:09:19 ERROR [org.jboss.as.arquillian.container.ServerSetupObserver] (main) - Setup task failed during setup. Offending class 'org.wildfly.camel.test.spring.redis.SpringRedisIntegrationTest$RedisServerSetupTask@307cf964'
java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:61)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at org.wildfly.camel.test.spring.redis.SpringRedisIntegrationTest$RedisServerSetupTask.setup(SpringRedisIntegrationTest.java:68)
```

**Comment by danielpereira90** [comment]
I also had this problem. In my case, the SSD didn't have enough space to instantiate a Reddis, since it requires some good amount of GB to able to run. I freed some space and everything worked as expected.

**Comment by tdiesler** [comment]
out-of-date
